Repository woowa-techcamp-2024/Team7-ELEVEN, pull requests merged in 2024-08, with the labels that each got.

#3 feat: skeleton domain
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/wootecam/luckyvickyauction/LuckyVickyAuctionApplication.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Product.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/.gitkeep
  src/main/java/com/wootecam/luckyvickyauction/global/.gitkeep
  src/main/resources/application.properties
  src/test/java/com/wootecam/luckyvickyauction/LuckyVickyAuctionApplicationTests.java
Labels: FEATURE

#6 docs: Spring Rest Docs 설정 추가
  build.gradle
  src/docs/asciidoc/docinfo.html
  src/docs/asciidoc/errorCode.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wootecam/luckyvickyauction/global/.gitkeep
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/documentation/documentation/DocumentationTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/documentation/ErrorCodeDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/documentation/errorcode/ErrorCodeFieldsSnippet.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/documentation/errorcode/FakeErrorCodeController.java
  src/test/resources/org/springframework/restdocs/templates/error-code-template.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: FEATURE

#7 Feat/5 action service building
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionSearchCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
Labels: FEATURE

#14 feat: member 로그인 (회원가입 통합), 로그아웃 로직 구현
  src/main/java/com/wootecam/luckyvickyauction/core/bid/domain/BidHistory.java
  src/main/java/com/wootecam/luckyvickyauction/core/bid/service/BidHistoryService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/MemberRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/service/MemberService.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/service/MemberServiceTest.java
Labels: FEATURE

#15 hotfix: CustomException의 ErrorCode 리턴 타입 변경
  src/main/java/com/wootecam/luckyvickyauction/global/exception/BadRequestException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/BusinessException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/CustomException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/GlobalAdvice.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/InfraStructureException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/NotFoundException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/UnauthorizedException.java
Labels: HOTFIX

#17 refactor: 로그인 (회원가입) 예외를 custom 예외로 변경
  src/main/java/com/wootecam/luckyvickyauction/core/member/service/MemberService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
Labels: REFACTOR

#23 feat: member domain을 Buyer, Seller로 분할한다.
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Buyer.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/MemberRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Role.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Seller.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/service/MemberService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/RoleTest.java
Labels: FEATURE

#26 feat: 구매자는 진행 중인 경매를 입찰할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/bid/domain/BidHistory.java
  src/main/java/com/wootecam/luckyvickyauction/core/bid/service/BidHistoryService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Buyer.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Point.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Seller.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/service/MemberService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/.gitkeep
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistory.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistoryRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/BuyerTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/PointTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
Labels: FEATURE

#25 feat: 경매 생성 명령을 받아 경매를 생성한다. (중간 PR)
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/BadRequestException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/BusinessException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/CustomException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorResponse.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/GlobalAdvice.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/InfraStructureException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/NotFoundException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/UnauthorizedException.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/resources/org/springframework/restdocs/templates/error-code-template.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: FEATURE

#34 feat: 경매 생성 명령을 받아 경매를 생성한다. (중간 PR-2)
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionType.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentageAuctionType.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicyTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicyTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: FEATURE

#35 feat: 경매 생성 서비스 구현
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicyTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicyTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/ProductTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: DUPLICATE

#38 refactor: Seller와 Buyer를 Member로 합친다.
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Buyer.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Point.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Seller.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/MemberTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/PointTest.java
Labels: REFACTOR

#37 feat: 경매 옵션 변경(업데이트) 서비스 구현
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionStatus.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: FEATURE

#42 refactor: 진행중인 경매 입찰 로직 구현
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/MemberRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Point.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistory.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidStatus.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/MemberTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/PointTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
Labels: FEATURE, REFACTOR

#44 docs: story yml 추가
  .github/ISSUE_TEMPLATE/story.yml
Labels: DOCS

#53 feat: 비회원은 회원가입을 할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionSearchCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/dto/SignUpInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/service/MemberService.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/MemberTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/service/MemberServiceTest.java
Labels: FEATURE, REFACTOR

#55 feat: 사용자는 단일 경매를 상세 조회할 수 있다
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfoTest.java
Labels: FEATURE

#57 feat: 사용자의 세션 로그인 기능을 구현한다.
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/MemberRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/dto/SignInInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/dto/SignInRequestInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/dto/SignUpRequestInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/service/MemberService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/ProductTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/service/MemberServiceTest.java
Labels: FEATURE

#59 feat: 경매는 재고보다 많은 양의 사용자 요청을 처리할 수 없다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: FEATURE

#65 feat: 판매자가 등록한 경매의 정책을 변경할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: FEATURE

#66 refactor: 사용자 로그인 시 인자로 HttpSession을 받지 않고, 응답으로 로그인 할 사용자의 정보를 반환한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/service/MemberService.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/MemberTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/repository/FakeMemberRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/service/MemberServiceTest.java
Labels: REFACTOR

#68 feat: 경매의 상태는 시작전, 진행중, 품절, 종료 상태가 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionStatus.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfoTest.java
Labels: FEATURE

#70 test: Member 도메인 단위 테스트를 추가한다.
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/MemberTest.java
Labels: TEST

#67 feat: 사용자는 환불 시에 환불액을 주고 받는다
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistory.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistoryRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/MemberTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
Labels: FEATURE

#86 fix: AsciiDoc 생성 시 포맷 깨지는 현상을 수정한다.
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/MemberTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ErrorCodeDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/errorcode/ErrorCodeFieldsSnippet.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/errorcode/FakeErrorCodeController.java
  src/test/resources/org/springframework/restdocs/templates/error-code-template.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: FIX

#85 feat: 경매는 진행 중 상태가 아니면 사용자의 요청을 처리할 수 없다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionStatus.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/repository/FakeAuctionRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: FEATURE

#100 feat: 판매자는 자신이 등록한 경매의 재고를 변경할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/dto/SignInInfo.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: FEATURE

#108 hotfix: 컴파일 에러를 수정한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/repository/FakeAuctionRepository.java
Labels: HOTFIX

#121 test: changeStock에 대한 서비스 테스트를 추가합니다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/repository/FakeAuctionRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/repository/FakeMemberRepository.java
Labels: REFACTOR, TEST

#110 feat: 사용자는 자신의 포인트를 충전할 수 있다
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Point.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/PointTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
Labels: FEATURE

#124 feat: Create, UpdateAuctionCommad 생성 시 시작시간보다 요청시간이 늦어야 하는 정합성 검증을 추가한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: FEATURE, REFACTOR

#122 feat: 사용자는 자신의 거래 내역을 확인(단건 조회)할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistory.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/repository/FakeBidHistoryRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
Labels: FEATURE

#131 refactor: 경매는 현재 재고량을 확인할 수 있다
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/repository/FakeAuctionRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: REFACTOR

#132 feat: 판매자는 거래 내역 상세 조회시, 자신의 경매 상품의 거래내역을 조회할 수 있다.
  src/test/java/com/wootecam/luckyvickyauction/LuckyVickyAuctionApplicationTests.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
Labels: FEATURE

#135 fix: 경매 재고 수정 시 WAITING 상태인 경매만 수정할 수 있는 검증 로직을 추가합니다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionStockCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: FIX

#147 refactor: Auction의 status 필드를 삭제한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/repository/FakeAuctionRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: REFACTOR

#148 feat: 경매는 환불을 하면 자신의 재고를 증가할 수 있다
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: FEATURE

#168 feat: 경매는 경매 취소 요청을 처리한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CancelAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/fixture/AuctionFixture.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/repository/FakeAuctionRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/CancelAuctionTest.java
Labels: FEATURE, REFACTOR

#176 refactor: 사용자는 환불 시에 환불액을 주고 받는다
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/fixture/AuctionFixture.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/fixture/MemberFixture.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
Labels: TEST

#179 refactor: 판매자가 경매 상세 조회시 다음 정보를 조회할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionInfoTest.java
Labels: REFACTOR

#180 feat: 구매자는 거래 내역 목록에서 다음 정보를 확인할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistoryRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSimpleInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/ReceiptSelectCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryService.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/repository/FakeBidHistoryRepository.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
Labels: FEATURE

#178 feat: 거래 내역은 경매 식별자, 구매(입찰) 가격, 구매 수량, 거래 유형(입찰, 환불), 구매자, 판매자, 생성일자를 포함한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistory.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/repository/FakeBidHistoryRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
Labels: FEATURE

#184 feat: 판매자는 다른 판매자의 경매 상품을 상세 조회할 수 없다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/dto/SignInInfo.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/GetSellerAuctionTest.java
Labels: FEATURE

#182 feat: 구매자가 경매 목록 조회시 다음 정보를 포함한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionSimpleInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/repository/FakeAuctionRepository.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
Labels: FEATURE

#186 feat: 판매자는 경매 상품 목록에서 경매 식별자, 원가, 현재 판매가, 총 제고량, 현재 제고량, 시작시간, 종료시간을 확인할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionSearchCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionSimpleInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/repository/FakeAuctionRepository.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
Labels: FEATURE

#188 feat: 구매자는 거래 목록을 최대 100개까지 한번에 조회할 수 있다
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistoryRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSearchCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/ReceiptSelectCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSelectConditionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/repository/FakeBidHistoryRepository.java
Labels: FEATURE

#190 feat: 회원 ID의 제약 사항을 구현한다.
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/dto/SignUpRequestInfo.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/MemberTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/dto/SignUpRequestInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
Labels: FEATURE

#189 feat: 회원의 비밀번호 제약 구현
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/MemberTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/ValidatePasswordTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/fixture/MemberFixture.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/service/MemberServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
Labels: FEATURE

#181 feat: Auction 내부에서 경매 지속시간에 대한 검증을 진행합니다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicyTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicyTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/fixture/AuctionFixture.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
Labels: FEATURE

#196 feat: Repository 클래스 생성
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/entity/AuctionEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionJpaRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/entity/MemberEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/infra/MemberCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/infra/MemberJpaRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/entity/ReceiptEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptJpaRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/infra/FakeAuctionRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/CancelAuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/GetSellerAuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/infra/FakeMemberRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/service/MemberServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/FakeBidHistoryRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
Labels: FEATURE

#197 feat: Controller를 설계한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/AuthController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/controller/PaymentController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/controller/ReceiptController.java
Labels: FEATURE

#201 feat: 시작시간, 종료시간, 사용자의 요청시간을 이용해 현재 가격과 구매자가 입력한 가격이 맞는지 검증하고 재고를 감소시킨다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicyTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicyTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: FEATURE

#202 feat: 구매자는 자신의 거래 목록만을 조회할 수 있다.
  build.gradle
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistory.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/entity/ReceiptEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptJpaRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryImpl.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/config/JpaConfig.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/GetSellerAuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/fixture/MemberFixture.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/FakeBidHistoryRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
  src/test/resources/application.yaml
Labels: FEATURE, REFACTOR, BUG

#206 feat: 회원가입 성공시 회원 정보는 영구적으로 저장된다.
  src/main/java/com/wootecam/luckyvickyauction/core/member/entity/MemberEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/infra/MemberCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/infra/MemberJpaRepository.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/RepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/infra/MemberCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperMemberTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
Labels: FEATURE

#204 feat: 구매자 경매 목록 조회 페이지네이션
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionSearchCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/entity/AuctionEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionJpaRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionQueryDslRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionQueryDslRepositoryImpl.java
  src/test/java/com/wootecam/luckyvickyauction/context/RepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionSearchConditionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionQueryDslRepositoryTest.java
Labels: FEATURE

#210 feat: 판매자는 거래 목록을 최대 100개까지 한번에 조회할 수 있다
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryImpl.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryTest.java
Labels: FEATURE

#209 feat: 경매 상세 조회 SQL 작성 및 연동
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PricePolicyType.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/entity/AuctionEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/entity/PricePolicyConverter.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/entity/PricePolicyConverterTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
Labels: FEATURE

#213 feat: 사용자는 REST API를 통해서 로그인 요청을 할 수 있다.
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/AuthController.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/dto/SignInRequestInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/dto/SignUpRequestInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/infra/MemberCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/service/MemberService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/SellerReceiptSimpleInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/GlobalAdvice.java
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/dto/SignUpRequestInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/service/MemberServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/AuthDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentFormatGenerator.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
Labels: FEATURE

#212 feat: 판매자가 경매를 수정하면 영구적으로 변경이 반영된다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/entity/AuctionEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/RepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/context/RepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/infra/MemberCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperAuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
Labels: FEATURE, REFACTOR

#211 feat: 회원가입 API를 구현한다.
  src/docs/asciidoc/auth.adoc
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/AuthController.java
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/documentation/AuthDocument.java
Labels: FEATURE

#219 feat: 구매자는 REST API를 통해서 경매를 상세 조회 요청을 할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/fixture/BuyerAuctionInfoFixture.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
Labels: FEATURE

#215 feat: 거래 내역은 영구적으로 저장 관리된다
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperReceiptTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
Labels: FEATURE

#223 feat: 구매자는 REST API를 통해서 경매 목록을 조회할 수 있다.
  src/docs/asciidoc/auctions.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/AuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
Labels: FEATURE

#221 feat: 사용자는 REST API를 통해서 거래 내역 목록 조회 요청을 보낼 수 있다.
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/receipts.adoc
  src/main/java/com/wootecam/luckyvickyauction/core/payment/controller/ReceiptController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSimpleInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/SellerReceiptSimpleInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryService.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ReceiptDocument.java
Labels: FEATURE

#226 feat: 판매자는 REST API를 통해서 경매 상품 목록 조회 요청을 수행할 수 있다.
  src/docs/asciidoc/auctions.adoc
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionController.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/AuctionDocument.java
Labels: FEATURE

#224 feat: 사용자가 특정 API endpoint에 접근할 수 있는 권한이 있는지 검사할 수 있어야 합니다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/entity/AuctionEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/AuthenticationInterceptor.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/BuyerOnly.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/Roles.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/SellerOnly.java
  src/main/java/com/wootecam/luckyvickyauction/global/config/WebConfig.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/AuthDocument.java
Labels: FEATURE

#225 feat: 사용자는 REST API를 통해서 거래 내역 상세 조회 기능을 사용할 수 있다
  src/docs/asciidoc/auctions.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/receipt.adoc
  src/main/java/com/wootecam/luckyvickyauction/core/payment/controller/ReceiptController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryService.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ReceiptDocument.java
Labels: FEATURE

#222 feat: 구매자는 REST API를 통해서 포인트 충전 요청을 할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/controller/PaymentController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerChargePointCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/fixture/MemberFixture.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/controller/PaymentControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ReceiptDocument.java
Labels: FEATURE

#230 feat: 판매자는 REST API를 통해서 경매 취소 요청을 수행할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionController.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionControllerTest.java
Labels: FEATURE

#231 feat: 구매자 구매 취소 REST API 개발
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
Labels: FEATURE

#232 feat: 로그인 한 사용자가 접근하면 사용자의 권한을 추출 및 저장할 수 있어야 합니다.
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/AuthenticationArgumentResolver.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/AuthenticationInterceptor.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/Login.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/AuthenticationContext.java
  src/main/java/com/wootecam/luckyvickyauction/global/config/WebConfig.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/AuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ReceiptDocument.java
Labels: FEATURE

#234 feat: 구매(입찰) REST API 개발
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/dto/BidRequest.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/AuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
Labels: FEATURE

#241 refactor: ArgumentResolver로 전달받은 Authentication(인증된 사용자)를 필요한 서비스 인자로 넘겨주는 작업을 한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionJpaRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/controller/PaymentController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/controller/ReceiptController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistory.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistoryRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSearchCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/SellerReceiptSearchCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptJpaRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryImpl.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/fixture/CreateAuctionCommandFixture.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/GetSellerAuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/controller/PaymentControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSelectConditionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/SellerReceiptSelectConditionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/FakeBidHistoryRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/AuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ReceiptDocument.java
Labels: FEATURE, REFACTOR

#245 refactor: 사용하지 않는 경매 수정, 재고 수정 로직을 삭제한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionStockCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/UpdateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: REFACTOR

#247 feat: 현재 시간을 가져와 주는 ArgumentResolver 등록
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/CurrentTime.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/CurrentTimeArgumentResolver.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/dto/CreateAuctionRequest.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/global/config/WebConfig.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/fixture/CreateAuctionCommandFixture.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
Labels: FEATURE

#249 refactor: FakeRepository를 H2 Inmemory를 적용한다
  src/main/resources/application.yaml
  src/test/java/com/wootecam/luckyvickyauction/context/DatabaseCleaner.java
  src/test/java/com/wootecam/luckyvickyauction/context/RepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/context/ServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/context/SpringBootTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/infra/FakeAuctionRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/CancelAuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/GetSellerAuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/fixture/MemberFixture.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/infra/FakeMemberRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/service/MemberServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/FakeBidHistoryRepository.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
  src/test/resources/application.yaml
Labels: REFACTOR

#250 refactor: Rest Docs API 문서를 정리한다
  .github/workflows/static.yml
  src/docs/asciidoc/auctions.adoc
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/buyerAuctions.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/memberAuctions.adoc
  src/docs/asciidoc/point.adoc
  src/docs/asciidoc/receipt.adoc
  src/docs/asciidoc/receipts.adoc
  src/docs/asciidoc/sellerAuctions.adoc
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionSimpleInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/controller/PaymentController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/controller/ReceiptController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidStatus.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionControllerTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/AuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/AuthDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/BuyerAuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/PaymentDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ReceiptDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/SellerAuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperReceiptTest.java
Labels: REFACTOR

#251 docs: api docs 배포 주소 readme 추가
  README.md
Labels: DOCS

#252 refactor: ZonedDateTime -> LocalDateTime 변경
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/CurrentTimeArgumentResolver.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/dto/CreateAuctionRequest.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionSimpleInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CancelAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionSimpleInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/entity/AuctionEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistory.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/entity/ReceiptEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/fixture/AuctionFixture.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/fixture/BuyerAuctionInfoFixture.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BidHistoryInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/BidHistoryServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/BuyerAuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ReceiptDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/SellerAuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperAuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperReceiptTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
Labels: REFACTOR

#253 refactor: A007 -> G000으로 변경하고 에러코드 순서를 재정렬한다.
  build.gradle
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/dto/BidRequest.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CancelAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommand.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/entity/PricePolicyConverter.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistory.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/ConstantPricePolicyTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/PercentagePricePolicyTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/AuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/SellerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/domain/BidHistoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
Labels: REFACTOR

#254 refactor(test): 테스트 제목을 일관성있는 한글로 변경합니다.
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/CreateAuctionCommandTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/MemberTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/ValidatePasswordTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSelectConditionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/SellerReceiptSelectConditionTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/BuyerAuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ErrorCodeDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/PaymentDocument.java
Labels: REFACTOR

#257 feat: service에 `@Transactional` 어노테이션 적용
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/service/MemberService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/ReceiptService.java
Labels: FEATURE

#260 refactor: `@CurrentTime`으로 현재 시간을 가져오도록 변경한다
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
Labels: REFACTOR

#264 refactor: 사용자 로그인을 하면 자신의 역할에 맞는 페이지로 이동한다
  src/docs/asciidoc/auth.adoc
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/AuthController.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/dto/SignInResponseInfo.java
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/documentation/AuthDocument.java
Labels: REFACTOR

#268 feat: cors 설정을 적용한다.
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/AuthenticationInterceptor.java
  src/main/java/com/wootecam/luckyvickyauction/global/config/WebConfig.java
Labels: FEATURE

#266 refactor: 사용자 경매 상세 조회시 원래 재고값도 응답하도록 변경합니다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Product.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfo.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/core/auction/dto/BuyerAuctionInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/fixture/BuyerAuctionInfoFixture.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/BuyerAuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentFormatGenerator.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/PaymentDocument.java
Labels: REFACTOR

#269 refactor: 사용자는 offset을 지정하여 거래 내역을 어디서 부터 조회할지 지정할 수 있다.
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSearchCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/SellerReceiptSearchCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryImpl.java
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSelectConditionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/SellerReceiptSelectConditionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/ReceiptServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ReceiptDocument.java
Labels: REFACTOR

#261 feat: Redis 사용을 위한 프로젝트 환경 구성
  build.gradle
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionLockOperation.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/Auctioneer.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/AuctioneerProxy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/BasicAuctioneer.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/LettuceLockAuctioneerProxy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/RedissonLockAuctioneerProxy.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/config/RedisConfig.java
  src/main/resources/application.yaml
  src/test/java/com/wootecam/luckyvickyauction/context/EmbeddedRedisConfig.java
  src/test/java/com/wootecam/luckyvickyauction/context/ServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/BuyerAuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
  src/test/resources/application.yaml
Labels: FEATURE

#235 feat: 모니터링 환경 구성
  build.gradle
  infra/docker-compose.yaml
  infra/grafana/dashboards/spring-actuator-dashboard.json
  infra/grafana/provisioning/dashboards/dashboards.yml
  infra/grafana/provisioning/datasources/prometheus.yml
  infra/prometheus/prometheus.yml
  src/main/java/com/wootecam/luckyvickyauction/global/config/MetricConfig.java
  src/main/resources/application.yaml
Labels: FEATURE

#272 refactor: 세션 사용자 없을때 Authentication 예외를 발생시킨다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/AuthenticationInterceptor.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/ReceiptService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/AuthenticationException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/AuthorizationException.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/GlobalAdvice.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/UnauthorizedException.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/ReceiptServiceTest.java
Labels: REFACTOR

#273 refactor: 모든 목록 조회 시 쿼리 파라미터로 offset, size 받도록 변경한다
  src/docs/asciidoc/memberAuctions.adoc
  src/docs/asciidoc/receipts.adoc
  src/docs/asciidoc/sellerAuctions.adoc
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/SellerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/dto/SellerAuctionSearchRequest.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/controller/ReceiptController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSearchCondition.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/SellerReceiptSearchCondition.java
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSelectConditionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/SellerReceiptSelectConditionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/ReceiptServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/BuyerAuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ReceiptDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/SellerAuctionDocument.java
Labels: REFACTOR

#275 feat: 경매 할인 주기 시간이 경매 시간보다 크거나 같고, 지정된 시간이 아니라면 예외가 발생하는 검증 추가
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
Labels: BUG

#279 refactor: 모든 목록 조회를 id 내림차순(최신 목록 부터) 조회로 변경한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionQueryDslRepositoryImpl.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryImpl.java
  src/main/resources/application.yaml
Labels: REFACTOR

#281 fix: 실패하는 테스트를 수정하고, 테스트 스크립트를 추가한다.
  .github/workflows/test_run.yml
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/resources/application.yaml
  src/test/java/com/wootecam/luckyvickyauction/context/ServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionQueryDslRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/ReceiptServiceTest.java
Labels: FIX

#285 bug: 거래 내역은 환불 시에 경매 식별자를 가져야 한다
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/BasicAuctioneer.java
Labels: BUG

#286 refactor: 종료된 경매상품만 환불할 수 있는 검증 로직을 추가한다
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
Labels: REFACTOR

#290 front: api url 변경
  front/.env
  front/src/api/payments/api.ts
  front/src/pages/ChargePoint.tsx
Labels: FRONT

#293 fix: Redisson 패스워드 설정 구문 추가
  src/main/java/com/wootecam/luckyvickyauction/global/config/RedisConfig.java
  src/test/java/com/wootecam/luckyvickyauction/context/EmbeddedRedisConfig.java
Labels: BUG

#296 feat: 구매자 입찰 과정은 원자적으로 처리되어야한다.
  src/main/java/com/wootecam/luckyvickyauction/core/auction/infra/AuctionLockOperation.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/AuctioneerProxy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/BasicAuctioneer.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/LettuceLockAuctioneerProxy.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/RedissonLockAuctioneerProxy.java
  src/main/java/com/wootecam/luckyvickyauction/core/lock/LettuceLockProvider.java
  src/main/java/com/wootecam/luckyvickyauction/core/lock/NoOperationLockProvider.java
  src/main/java/com/wootecam/luckyvickyauction/core/lock/RedissonLockProvider.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Member.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/domain/Point.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/aop/DistributedLock.java
  src/main/java/com/wootecam/luckyvickyauction/global/aop/DistributedLockAspect.java
  src/main/java/com/wootecam/luckyvickyauction/global/aop/LockProvider.java
  src/main/java/com/wootecam/luckyvickyauction/global/config/LockProviderConfig.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ServiceUnavailableException.java
  src/main/resources/application.yaml
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/MemberTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/member/domain/PointTest.java
  src/test/resources/application.yaml
Labels: FEATURE

#294 feat: Redis Stream 연동을 위한 기반 코드 작성
  build.gradle
  src/main/java/com/wootecam/luckyvickyauction/consumer/config/RedisStreamConfig.java
  src/main/java/com/wootecam/luckyvickyauction/consumer/presentation/PendingMessageConsumer.java
  src/main/java/com/wootecam/luckyvickyauction/consumer/presentation/RedisOperator.java
  src/main/java/com/wootecam/luckyvickyauction/consumer/presentation/RedisStreamConsumer.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/Auctioneer.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/BasicAuctioneer.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/LazyAuctioneer.java
  src/main/java/com/wootecam/luckyvickyauction/global/dto/AuctionPurchaseRequestMessage.java
  src/main/java/com/wootecam/luckyvickyauction/global/dto/AuctionRefundRequestMessage.java
  src/main/resources/application.yaml
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/context/RepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/context/ServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/BuyerAuctionDocument.java
  src/test/resources/application-test.yaml
Labels: FEATURE

#299 feat: 갑자기 Front가 눈에 들어왔어요.
  front/package-lock.json
  front/src/App.tsx
  front/src/img/alert-circle.svg
  front/src/img/arrow-left.svg
  front/src/img/credit-card.svg
  front/src/img/list.svg
  front/src/img/log-in.svg
  front/src/img/log-out.svg
  front/src/img/shopping-bag.svg
  front/src/index.css
  front/src/pages/AlertPage.tsx
  front/src/pages/ChargePoint.tsx
  front/src/pages/Footer.tsx
  front/src/pages/Header.tsx
  front/src/pages/Login.tsx
  front/src/pages/SignUp.tsx
  front/src/pages/auction/detail/AuctionDetail.tsx
  front/src/pages/auction/list/AuctionList.tsx
  front/src/pages/auction/list/AuctionListElement.tsx
  front/src/pages/receipt/detail/ReceiptDetail.tsx
  front/src/pages/receipt/list/ReceiptList.tsx
  front/src/pages/receipt/list/ReceiptListElement.tsx
  front/src/store/PageStore.ts
  front/src/util/DateUtil.ts
  src/main/java/com/wootecam/luckyvickyauction/global/config/WebConfig.java
  src/test/resources/application-test.yaml
Labels: FRONT

#295 chore: EC2 배포 플로우를 작성한다.
  .github/workflows/dev_code_deploy.yml
  .gitignore
  build.gradle
  deploy.sh
  front/.env
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/controller/AuthenticationInterceptor.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/dto/AuctionPurchaseRequestMessage.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/docs/index.html
  src/main/resources/static/index.html
  src/test/java/com/wootecam/luckyvickyauction/context/RepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/context/ServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/resources/application-test.yaml
  src/test/resources/application.yml
Labels: CHORE

#301 feat: 환불 요청 대기열 처리 기능 구현
  src/main/java/com/wootecam/luckyvickyauction/consumer/presentation/PendingMessageConsumer.java
  src/main/java/com/wootecam/luckyvickyauction/consumer/presentation/RedisStreamConsumer.java
  src/main/java/com/wootecam/luckyvickyauction/consumer/service/MessageRouterService.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/LazyAuctioneer.java
Labels: FEATURE

#310 refactor: 입찰 완료 시 거래내역 ID를 반환하기
  src/docs/asciidoc/buyerAuctions.adoc
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/BuyerAuctionController.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/controller/dto/PurchaseResponse.java
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/BasicAuctioneer.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/controller/ReceiptController.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/Receipt.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/domain/ReceiptRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/BuyerReceiptSimpleInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/ReceiptInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/dto/SellerReceiptSimpleInfo.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/entity/ReceiptEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptJpaRepository.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/ReceiptService.java
  src/main/java/com/wootecam/luckyvickyauction/global/dto/AuctionPurchaseRequestMessage.java
  src/main/java/com/wootecam/luckyvickyauction/global/dto/AuctionRefundRequestMessage.java
  src/main/resources/docs/index.html
  src/test/java/com/wootecam/luckyvickyauction/context/DatabaseCleaner.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/domain/ReceiptTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/dto/ReceiptInfoTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptCoreRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/infra/ReceiptQueryDslRepositoryTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/ReceiptServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/BuyerAuctionDocument.java
  src/test/java/com/wootecam/luckyvickyauction/documentation/ReceiptDocument.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperReceiptTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperTest.java
Labels: REFACTOR

#312 refactor: 경매 생성 시 설정 가능한 경매 시간 및 적용할 수 있는 할인 주기를 다양하게 설정할 수 있게 검증을 변경합니다.
  .github/workflows/test_run.yml
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/core/member/entity/MemberEntity.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/entity/ReceiptEntity.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/java/com/wootecam/luckyvickyauction/global/util/Mapper.java
  src/main/resources/application-dev.yml
  src/main/resources/docs/index.html
  src/test/java/com/wootecam/luckyvickyauction/context/EmbeddedRedisConfig.java
  src/test/java/com/wootecam/luckyvickyauction/context/ServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/BasicAuctioneerTest.java
  src/test/java/com/wootecam/luckyvickyauction/global/util/MapperMemberTest.java
Labels: REFACTOR

#315 refactor: Auction생성 시 할인하지 않는 경우도 등록할 수 있는 검증 추가!
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentServiceTest.java
Labels: REFACTOR

#319 fix: conflict로 사라진 에러 코드 재적용
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionService.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
Labels: FIX

#321 refactor: 경매 구매 요청 시 경매 재고가 부족하다면 200응답을 주도록 변경한다.
  README.md
  src/main/java/com/wootecam/luckyvickyauction/core/auction/domain/Auction.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/ErrorCode.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/GlobalAdvice.java
  src/main/java/com/wootecam/luckyvickyauction/global/exception/SuccessfulOperationException.java
  src/main/resources/docs/index.html
  src/test/java/com/wootecam/luckyvickyauction/core/auction/domain/AuctionTest.java
  src/test/java/com/wootecam/luckyvickyauction/core/auction/service/AuctionServiceTest.java
Labels: REFACTOR

#325 front: 초 단위 가격 갱신 적용 및 재고 부족 시 응답이 200으로 오는 부분에 맞게 수정
  front/src/api/auction/api.ts
  front/src/api/auction/type.ts
  front/src/pages/auction/detail/AuctionDetail.tsx
  front/src/pages/auction/detail/PricePolicyElement.tsx
  front/src/util/DateUtil.ts
Labels: FRONT

#328 refactor: UUID -> UUID.toString()으로 변경합니다.
  api/src/main/java/com/wootecam/luckyvickyauction/controller/BuyerAuctionController.java
  api/src/main/java/com/wootecam/luckyvickyauction/controller/ReceiptController.java
  api/src/main/java/com/wootecam/luckyvickyauction/dto/PurchaseResponse.java
  api/src/test/java/com/wootecam/luckyvickyauction/documentation/ReceiptDocument.java
  consumer/src/main/java/com/wootecam/luckyvickyauction/service/BasicAuctioneer.java
  consumer/src/test/java/com/wootecam/luckyvickyauction/service/BasicAuctioneerTest.java
  core/src/main/java/com/wootecam/luckyvickyauction/domain/entity/Receipt.java
  core/src/main/java/com/wootecam/luckyvickyauction/domain/repository/ReceiptRepository.java
  core/src/main/java/com/wootecam/luckyvickyauction/dto/auction/message/AuctionPurchaseRequestMessage.java
  core/src/main/java/com/wootecam/luckyvickyauction/dto/auction/message/AuctionRefundRequestMessage.java
  core/src/main/java/com/wootecam/luckyvickyauction/dto/receipt/info/BuyerReceiptSimpleInfo.java
  core/src/main/java/com/wootecam/luckyvickyauction/dto/receipt/info/ReceiptInfo.java
  core/src/main/java/com/wootecam/luckyvickyauction/dto/receipt/info/SellerReceiptSimpleInfo.java
  core/src/main/java/com/wootecam/luckyvickyauction/infra/entity/receipt/ReceiptEntity.java
  core/src/main/java/com/wootecam/luckyvickyauction/infra/repository/receipt/ReceiptCoreRepository.java
  core/src/main/java/com/wootecam/luckyvickyauction/infra/repository/receipt/ReceiptJpaRepository.java
  core/src/main/java/com/wootecam/luckyvickyauction/service/receipt/ReceiptService.java
  core/src/test/java/com/wootecam/luckyvickyauction/domain/entity/ReceiptTest.java
  core/src/test/java/com/wootecam/luckyvickyauction/dto/receipt/info/ReceiptInfoTest.java
  core/src/test/java/com/wootecam/luckyvickyauction/infra/repository/receipt/ReceiptCoreRepositoryTest.java
  core/src/test/java/com/wootecam/luckyvickyauction/infra/repository/receipt/ReceiptQueryDslRepositoryTest.java
  core/src/test/java/com/wootecam/luckyvickyauction/service/receipt/ReceiptServiceTest.java
  core/src/test/java/com/wootecam/luckyvickyauction/util/MapperReceiptTest.java
  core/src/test/java/com/wootecam/luckyvickyauction/util/MapperTest.java
Labels: REFACTOR

#331 feat: 경매 입찰 요청이 실패한 경우 거래 실패 내역 생성 대응 로직 구현
  api/build.gradle
  api/src/main/java/com/wootecam/luckyvickyauction/config/JsonConfig.java
  api/src/main/java/com/wootecam/luckyvickyauction/controller/BuyerAuctionController.java
  api/src/main/java/com/wootecam/luckyvickyauction/service/LazyAuctioneer.java
  api/src/test/java/com/wootecam/luckyvickyauction/documentation/DocumentationTest.java
  consumer/build.gradle
  consumer/src/main/java/com/wootecam/luckyvickyauction/config/RedisStreamConfig.java
  consumer/src/main/java/com/wootecam/luckyvickyauction/presentation/RedisStreamConsumer.java
  consumer/src/main/java/com/wootecam/luckyvickyauction/service/BasicAuctioneer.java
  consumer/src/main/java/com/wootecam/luckyvickyauction/service/MessageRouterService.java
  consumer/src/test/java/com/wootecam/luckyvickyauction/service/MessageRouterServiceTest.java
  core/src/main/java/com/wootecam/luckyvickyauction/domain/entity/type/ReceiptStatus.java
  core/src/main/java/com/wootecam/luckyvickyauction/dto/auction/message/AuctionPurchaseRequestMessage.java
  core/src/main/java/com/wootecam/luckyvickyauction/dto/receipt/command/CreateReceiptCommand.java
  core/src/main/java/com/wootecam/luckyvickyauction/service/auctioneer/Auctioneer.java
  core/src/main/java/com/wootecam/luckyvickyauction/service/receipt/ReceiptService.java
  core/src/test/java/com/wootecam/luckyvickyauction/service/receipt/ReceiptServiceTest.java
Labels: FEATURE

#332 feat: version2 경매 입찰 대기 페이지 구현
  front/src/App.tsx
  front/src/api/receipt/type.ts
  front/src/pages/auction/WaitingPage.tsx
  front/src/pages/auction/detail/AuctionDetail.tsx
Labels: FRONT

#333 feat: dev2 Auctioneer 입찰 로직 실행 시간 측정 메트릭 적용
  api/src/main/java/com/wootecam/luckyvickyauction/config/MetricConfig.java
  api/src/main/java/com/wootecam/luckyvickyauction/service/LazyAuctioneer.java
  infra/grafana/dashboards/spring-actuator-dashboard.json
Labels: FEATURE

#337 fix: 대기열 페이지에서 receiptId를 조회하지 못하는 버그 수정
  front/src/api/auction/api.ts
  front/src/api/auction/type.ts
  front/src/pages/auction/detail/AuctionDetail.tsx
Labels: HOTFIX

#339 fix: 영수증 응답을 답는 DTO의 Key이름을 서버와 동일하게 수정
  front/src/api/auction/api.ts
  front/src/api/auction/type.ts
Labels: HOTFIX, FRONT

#341 chore: redisson lease time 200초 설정
  src/main/resources/application-dev.yml
Labels: Senario

#340 feat: dev2 경매 실패 시 출력 로깅을 추가한다.
  consumer/src/main/java/com/wootecam/luckyvickyauction/config/RedisStreamConfig.java
  consumer/src/main/java/com/wootecam/luckyvickyauction/service/MessageRouterService.java
  core/src/main/java/com/wootecam/luckyvickyauction/config/JpaConfig.java
  core/src/main/java/com/wootecam/luckyvickyauction/infra/entity/receipt/ReceiptEntity.java
  core/src/main/java/com/wootecam/luckyvickyauction/infra/repository/receipt/ReceiptQueryDslRepositoryImpl.java
  core/src/test/java/com/wootecam/luckyvickyauction/infra/repository/receipt/ReceiptCoreRepositoryTest.java
Labels: FEATURE

#344 fix: Reddison Lock을 얻을 때 타임아웃이 발생한다면 unlock을 호출하지 않도록 한다.
  core/src/main/java/com/wootecam/luckyvickyauction/aop/DistributedLockAspect.java
Labels: REFACTOR

#345 feat: 분산락 타임아웃 상황에서 트랜잭션 롤백 문제 해결
  .github/workflows/test_run.yml
  src/main/java/com/wootecam/luckyvickyauction/core/auction/service/auctioneer/BasicAuctioneer.java
  src/main/java/com/wootecam/luckyvickyauction/core/payment/service/PaymentService.java
  src/main/java/com/wootecam/luckyvickyauction/global/aop/DistributedLockAspect.java
  src/main/java/com/wootecam/luckyvickyauction/global/aop/TransactionalTimeout.java
  src/main/java/com/wootecam/luckyvickyauction/global/aop/TransactionalTimeoutAspect.java
Labels: FEATURE

#346 feat: 트랜잭셔널 타임아웃 추가
  consumer/src/main/java/com/wootecam/luckyvickyauction/service/BasicAuctioneer.java
  core/src/main/java/com/wootecam/luckyvickyauction/aop/TransactionalTimeout.java
  core/src/main/java/com/wootecam/luckyvickyauction/aop/TransactionalTimeoutAspect.java
  core/src/main/java/com/wootecam/luckyvickyauction/service/payment/PaymentService.java
Labels: FEATURE
